In [34]:
import pandas as pd
import warnings

In [35]:
df = pd.read_excel('/Users/aliciacampbell/GitHub/pyline/EEG-pyline/Results/LEISURE_T1_T2/LEISURE_T1_T2_regions_aperiodiccomponents.xlsx')

In [36]:
# Filter for 'R_2' measure
r2_df = df[df['Measure'] == 'R_2']

# Melt the DataFrame to make 'Frontal', 'Temporal', 'Posterior' into row values
melted_df = r2_df.melt(id_vars=['Subject', 'Condition', 'Timepoint', 'Measure'], 
                       value_vars=['Frontal', 'Temporal', 'Posterior'], 
                       var_name='Region', value_name='R2_Value')

# Filter for rows where R2_Value is less than 0.9
filtered_df = melted_df[melted_df['R2_Value'] < 0.9]

# Select the required columns, including R2_Value
R2_df = filtered_df[['Subject', 'Condition', 'Timepoint', 'Region', 'R2_Value']]

In [37]:
# Filter for 'Error' measure
error_df = df[df['Measure'] == 'Error']

# Melt the DataFrame to make 'Frontal', 'Temporal', 'Posterior' into row values
melted_df = error_df.melt(id_vars=['Subject', 'Condition', 'Timepoint', 'Measure'], 
                          value_vars=['Frontal', 'Temporal', 'Posterior'], 
                          var_name='Region', value_name='Error_Value')

# Filter for rows where Error_Value is greater than 0.1
filtered_df = melted_df[melted_df['Error_Value'] > 0.1]

# Select the required columns, including Error_Value
errorabove_df = filtered_df[['Subject', 'Condition', 'Timepoint', 'Region', 'Error_Value']]

In [38]:
drop_t1_r2 = [sub for sub in R2_df['Subject'].unique() if 'T1' in sub]
drop_t2_r2 = [sub for sub in R2_df['Subject'].unique() if 'T2' in sub]

drop_t1_er = [sub for sub in errorabove_df['Subject'].unique() if 'T1' in sub]
drop_t2_er = [sub for sub in errorabove_df['Subject'].unique() if 'T2' in sub]

drop_man = ['HBA_0007_EC_T1', 'HBA_0007_EC_T2', 'HBA_0016_EC_T1', 'HBA_0060_EC_T2', 'HBA_0061_EC_T1']

drop = set(drop_t1_r2+drop_t2_r2+drop_t1_er+drop_t2_er+drop_man) # save this as excel for dropped subjects


df_dropped = df.loc[~df['Subject'].isin(drop)]
df_dropped = df_dropped.loc[df_dropped['Measure'].isin(['Exponent', 'Offset'])] # subjects dropped, save this as excel

In [39]:
pd.DataFrame(drop).to_excel('/Users/aliciacampbell/GitHub/pyline/EEG-pyline/Results/LEISURE_T1_T2/LEISURE_T1_T2_regions_aperiodiccomponents_droppedIDx.xlsx')

In [40]:
df_dropped.to_excel('/Users/aliciacampbell/GitHub/pyline/EEG-pyline/Results/LEISURE_T1_T2/LEISURE_T1_T2_regions_aperiodiccomponents_dropped.xlsx')

In [41]:
df_dropped

,Subject,Condition,Timepoint,Measure,Frontal,Temporal,Posterior
4,HBA_0003_EC_T1,EC,T1,Exponent,0.962709,0.546901,0.799960
5,HBA_0003_EC_T1,EC,T1,Offset,0.626953,0.513243,0.573478
8,HBA_0004_EC_T1,EC,T1,Exponent,1.189475,1.082115,0.836384
9,HBA_0004_EC_T1,EC,T1,Offset,0.632656,0.717941,0.429822
12,HBA_0005_EC_T1,EC,T1,Exponent,1.120204,1.155644,1.031116
...,...,...,...,...,...,...,...
693,HBA_0118_EC_T2,EC,T2,Offset,0.105113,0.367219,0.047389
708,HBA_0122_EC_T2,EC,T2,Exponent,0.854546,1.260949,1.197411
709,HBA_0122_EC_T2,EC,T2,Offset,0.068455,0.764142,0.638065
712,HBA_0126_EC_T2,EC,T2,Exponent,0.935171,1.033763,0.860792
713,HBA_0126_EC_T2,EC,T2,Offset,0.566697,0.603985,0.367872

In [42]:
df_dropped.loc[df_dropped['Timepoint']=='T2']

,Subject,Condition,Timepoint,Measure,Frontal,Temporal,Posterior
400,HBA_0001_EC_T2,EC,T2,Exponent,0.786256,0.656950,0.730681
401,HBA_0001_EC_T2,EC,T2,Offset,0.381525,0.692178,0.441703
408,HBA_0004_EC_T2,EC,T2,Exponent,1.217196,1.179666,0.653119
409,HBA_0004_EC_T2,EC,T2,Offset,0.631192,0.693696,0.281416
412,HBA_0005_EC_T2,EC,T2,Exponent,1.254577,1.237910,1.084671
...,...,...,...,...,...,...,...
693,HBA_0118_EC_T2,EC,T2,Offset,0.105113,0.367219,0.047389
708,HBA_0122_EC_T2,EC,T2,Exponent,0.854546,1.260949,1.197411
709,HBA_0122_EC_T2,EC,T2,Offset,0.068455,0.764142,0.638065
712,HBA_0126_EC_T2,EC,T2,Exponent,0.935171,1.033763,0.860792
713,HBA_0126_EC_T2,EC,T2,Offset,0.566697,0.603985,0.367872

Bad fits to drop manually that aren't included above already:

HBA_0007 T1	Frontal

HBA_0007 T2	Frontal

HBA_0016 T1	Temporal

HBA_0060 T2	Temporal

HBA_0061 T1	Frontal

HBA_0061 T1	Temporal